name: build
on:
  push: 
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'
      
      - name: Install dependancies
        run: cd server && npm ci

      - name: Check build
        run: cd server && npm run check

      - name: Run tests
        run : cd server && npm run test


