name: build
on:
  push: 
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 23, 24, 25]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # active le cache automatique pour npm
          cache: 'npm'
          cache-dependency-path: server/package-lock.json
      
      - name: Install dependancies
        run: cd server && npm ci

      - name: Check build
        run: cd server && npm run check

      - name: Run tests
        run : cd server && npm run test


